### ISSUE TITLE
青龙面板报错 KeyError: 'nonce'

### ISSUE THREAD

**Issue by wayner6** [CMDQ8575/Xiaomi-Community-AutoTask#4]
日志如下
```
Traceback (most recent call last):
  File "/ql/data/scripts/Xiaomi-community.py", line 130, in <module>
    main(account[i],password[i])
  File "/ql/data/scripts/Xiaomi-community.py", line 114, in main
    cookie = login(account,password)
  File "/ql/data/scripts/Xiaomi-community.py", line 95, in login
    sha1.update(('nonce=' + str(Auth['nonce']) + '&' + Auth['ssecurity']).encode('utf-8'))
KeyError: 'nonce'
```

**Comment by wayner6** [comment]
已经填写了用户名和密码

**Comment by rapmq0** [comment]
一样
